# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['Code\\main.py'],
    pathex=['C:\\Users\\javie\\Desktop\\Proyectos_GitHub\\Pokemon-Showdown-Python'],
    binaries=[],
    datas=[
        ('RawDatasets/Moves/Moves.json', 'RawDatasets/Moves'),
        ('RawDatasets/Movesets/gen1randombattle.json', 'RawDatasets/Movesets'),
        ('RawDatasets/Movesets/gen2randombattle.json', 'RawDatasets/Movesets'),
        ('RawDatasets/Movesets/gen3randombattle.json', 'RawDatasets/Movesets'),
        ('RawDatasets/Movesets/gen4randombattle.json', 'RawDatasets/Movesets'),
        ('RawDatasets/Movesets/gen5randombattle.json', 'RawDatasets/Movesets'),
        ('RawDatasets/Movesets/gen6randombattle.json', 'RawDatasets/Movesets'),
        ('RawDatasets/Movesets/gen7letsgorandombattle.json', 'RawDatasets/Movesets'),
        ('RawDatasets/Movesets/gen8bdsprandombattle.json', 'RawDatasets/Movesets'),
        ('RawDatasets/Movesets/gen8randombattle.json', 'RawDatasets/Movesets'),
        ('RawDatasets/Movesets/gen9randombattle.json', 'RawDatasets/Movesets'),
        ('RawDatasets/Pokemon/Pokemon.json', 'RawDatasets/Pokemon'),
    ],
    hiddenimports=[
        'Code',
        'Constructors.BaseConstructor',
        'Constructors.BattleConstructor',
        'Constructors.MoveConstructor',
        'Constructors.PlayerConstructor',
        'Constructors.PokemonConstructor',
        'Constructors.PokemonMoveSelector',
        'Constructors.PokemonStatsCalculator',
        'Constructors.SingletonBase',
        'Constructors.TeamConstructor',
        'DataProcessing.BaseProcessor',
        'DataProcessing.DataProcessor',
        'DataProcessing.MovesetProcessor',
        'DataProcessing.MovesProcessor',
        'DataProcessing.MoveTransformer',
        'DataProcessing.PokemonProcessor',
        'DataProcessing.PokemonTransformer',
        'DataProcessing.ProcessData',
        'DataStructures.Battle',
        'DataStructures.Move',
        'DataStructures.MoveExecution',
        'DataStructures.Player',
        'DataStructures.Pokemon',
        'DataStructures.Team',
        'Savers.BaseSaver',
        'Savers.BattleSaver',
        'Savers.PlayerSaver',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)


exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Alpha1_0',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
